server:
  port: 8010
spring:
  application:
    name: microservice-consumer-order
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    loadbalancer:
      retry:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

ribbon:
  OkToRetryOnAllOperations: false
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0
#  #请求处理的超时时间
#  ReadTimeout: 5000
#  #请求连接的超时时间
#  ConnectTimeout: 10000
  # 懒加载
  eager-load:
    enabled: true
    clients: UserFeignClient

hystrix:
  command:
    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000
      circuitBreaker:
        requestVolumeThreshold: 3
        sleepWindowInMilliseconds: 10000
        errorThresholdPercentage: 60

#  threadpool:
#    default:
#      coreSize: 20
#      maximumSize: 20

management:
  security:
    enabled: false


# 开启feign日志
logging.level.site.jackwang.cloud.study.user.feign.UserFeignClient: DEBUG

# 开启sleuth日志
logging.level.org.springframework.cloud.sleuth: info